In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [3]:
from sklearn.datasets import load_iris

In [4]:
iris=load_iris()

In [5]:
from sklearn.model_selection import cross_val_score

In [16]:
lr=cross_val_score(LogisticRegression(),iris.data,iris.target)
lr

C:\Users\bmvij\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [17]:
sv=cross_val_score(SVC(),iris.data,iris.target)
sv

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [18]:
dtc=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
dtc

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [19]:
rfc=cross_val_score(RandomForestClassifier(),iris.data,iris.target)
rfc

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [23]:
avg=[]

In [26]:
avg_lr=np.mean(lr)
avg.append(avg_lr)
avg_lr


0.9733333333333334

In [27]:
avg_sv=np.mean(sv)
avg.append(avg_sv)
avg_sv

0.9666666666666666

In [28]:
avg_dtc=np.mean(dtc)
avg.append(avg_dtc)
avg_dtc

0.9533333333333334

In [29]:
avg_rfc=np.mean(rfc)
avg.append(avg_rfc)
avg_rfc

0.9666666666666668

In [30]:
avg

[0.9733333333333334,
 0.9733333333333334,
 0.9733333333333334,
 0.9666666666666666,
 0.9533333333333334,
 0.9666666666666668]

In [31]:
max(avg)

0.9733333333333334