In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

In [6]:
digits=load_digits()

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [17]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\bmvij\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [18]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9796296296296296

In [19]:
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)
dtc.score(x_test,y_test)

0.8277777777777777

In [20]:
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)
rfc.score(x_test,y_test)

0.9592592592592593

In [21]:
def getscore(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [25]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [29]:
scores_lr=[]
scores_svm=[]
scores_dtc=[]
scores_rfc=[]

for train_index,test_index in folds.split(digits.data,digits.target):
    x_train,x_test,y_train,y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_lr.append(getscore(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_svm.append(getscore(SVC(),x_train,x_test,y_train,y_test))
    scores_dtc.append(getscore(DecisionTreeClassifier(),x_train,x_test,y_train,y_test))
    scores_rfc.append(getscore(RandomForestClassifier(),x_train,x_test,y_train,y_test))
    

C:\Users\bmvij\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\bmvij\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [30]:
scores_lr

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [31]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [32]:
scores_dtc

[0.7445742904841403, 0.8213689482470785, 0.7646076794657763]

In [33]:
scores_rfc

[0.9365609348914858, 0.9449081803005008, 0.9282136894824707]

In [34]:
from sklearn.model_selection import cross_val_score

In [35]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\bmvij\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\bmvij\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [36]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [37]:
cross_val_score(DecisionTreeClassifier(),digits.data,digits.target)

array([0.75555556, 0.725     , 0.80779944, 0.84122563, 0.79108635])

In [38]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.94166667, 0.9       , 0.9637883 , 0.95821727, 0.93314763])

In [42]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.93611111, 0.91388889, 0.95264624, 0.97214485, 0.9275766 ])